management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  data:
    mongodb:
      port: 27017
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    user:
      password: root
    oauth2:
      client:
        registration:
          keycloak:
              client-id: account
              client-secret: 8ba5b780-dd72-4d46-9521-3be3154a6aa1
              clientName: account
              authorization-grant-type: authorization_code
              redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
              scope:
                - openid
                - profile
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/certs
            user-name-attribute: preferred_username - email


server:
  error:
    include-stacktrace: never
  port: 9091
